<!-- outer wrapper start-->
<div id="outer_wrapper" class="clearfix posRel">
	<div id="photo_chooser"></div>
	<!-- left hand nav -->
	<div id="leftColumn" class="fleft">
	%%APPLICATION_LEFT_COLUMN%%
	<!-- left hand nav end -->
	</div> 
	<!-- inner start -->
	<div id="contentColumn" class="fright">
	
		<!-- <div id="applicationHeader" class="clearfix">
			%%APPLICATION_HEADER%%
		</div> -->
		<div id="applicationContent" class="clearfix">
			%%CONTENT_COLUMN%%
		</div>
	<!-- inner end -->
	</div>
</div>
<!-- outer wrapper end-->