<div class="popupDialog product_dialog addCategory_popUp">
<h3><img src="/Project/2_Enterprise/Design/Main_Layout/images/otherImages/plus.png" />Create New Category</h3>
	<div class="subCategory_entity">
		<form method="POST" action="/products/category/add">
			<div class="mBxl">
				<strong>Category Title</strong>
				<input class="validate[required,maxlength[45]] fright subCategory_entityTitle" type="text" name="title" maxlength="45">
			</div>
			<div class="mBxl">
				<strong>Url</strong><input class="fright subCategory_entityDescription" name="category_url" disabled="disabled"/>
			</div>
			<div id="button_container" class="fright mRs mBs">
				<input type="submit" class="save fleft mRs mTs" name="add_category" value=" ">
				<span class="mTs fleft pointer cancel" title="cancel"></span>
			</div>
		</form>
	</div>
</div>