<!-- outer wrapper start-->
<div id="outer_wrapper" class="clearfix">
	<!-- left hand nav -->
	<div id="leftColumn" class="fleft"> 
	%%APPLICATION_LEFT_COLUMN%%
	<!-- left hand nav end -->
	</div> 
	
	<!-- content column start -->
	<div id="contentColumn" class="fright">
		%%CONTENT_COLUMN%%
	<!-- content column end -->
	</div>
	
</div>
<!-- outer wrapper end-->
%%NEW_ALBUM_DIALOG%%
<div class="transparent_background hide"></div>