<? foreach($this->_get('array_of_products') as $products) : ?>
	<div class="featuredProduct">
		<img src="/Project/1_Website/Design/Main_Layout/images/new-product-indicator.png" class="newProductIndicator posAbs"/>
		<div class="productImage fleft" style="background-image:url('/Data/Images/corona-notebook-1_album/900x1024/toyota-supra-0.jpg');"></div>
		<div class="productDesciptionWrapper fleft">		
			<div class="fleft">
				<h3><?=$products->__get('product_name') ?></h3>
				<?=substr($products->__get('description'),1,50) ?>...
			</div>
			<div class="fright align_r">
				<? $list_price = explode('};{',$products->__get('pricing')) ?>
				<? $list_price = rtrim($list_price[1], '}'); ?>
				
				<span class="productPrice fright">List Price: $<?=$list_price ?></span><br>
				<? $price = explode('};{',$products->__get('pricing')) ?>
				<? $price = ltrim($price[0], '{'); ?>
				<b class="productPrice fontColorRed">$<?=$price ?></b>
				<a class="btnOrLink bgLightGreen fright" href="/<?=$products->__get('permalink') ?>">view product</a>
			</div>
		</div>		
	</div>	
<? endforeach; ?>