<? for($i=1; $i<=5; $i++) { ?>
	<div class="featuredProduct">
		<div class="productImage fleft" style="background-image:url('/Data/Images/corona-notebook-1_album/900x1024/toyota-supra-0.jpg');"></div>
		<div class="productDesciptionWrapper fleft">		
			<div class="fleft">
				<h3>featured title</h3>
				featured descipriotn
			</div>
			<div class="fright">
				<span class="productPrice fright">$200</span>
				<a class="btnOrLink bgBlue fright" href="">view product detail or add to shopping cart</a>
			</div>
		</div>		
		
		<!--<input type="hidden" name="product_id" value="<?//=$product->__get('product_id');?>">
		<input type="hidden" name="category_id" value="<?//=$product->__get('category_id');?>">-->
	</div>	
<? } ?>