<!--**************************************
				SCRIPT LINKS
 **************************************-->
 
<script src="Project/1_Website/Design/Main_Layout/scripts/cufon_yui.js" type="text/javascript"></script>
<script src="Project/1_Website/Design/Main_Layout/scripts/cufon.js" type="text/javascript"></script>
<script src="Project/1_Website/Design/Main_Layout/scripts/global_javascript.js" type="text/javascript"></script>

<!--**************************************
				PLUGIN LINKS
 **************************************-->
<script src="Project/1_Website/Design/Main_Layout/scripts/JQueryCorner_plugin.js" type="text/javascript"></script>
<script src="Project/1_Website/Design/Main_Layout/plugins/sharePlugin/jquery.share.js" type="text/javascript"></script>
