<div class="fleft">
	<h5>Login</h5>
	<form method="POST" class="login">
		<div class="row clearfix">
			<label>Username</label>
			<input type="text" name="username" class="required"/>
		</div>
		<div class="row clearfix">
			<label>Password</label>
			<input type="password" name="password" class="required"/>
		</div>
		<?php if($this->getLoginError()) :?>
		<div class="row clearfix">
			<label>Invalid Username or Password</label>
		</div>
		<?php endif ?>
		<div class="row clearfix">
			<label><a href = "/user/forgot_password">Forgot Password?</a></label>
		</div>
		<div class="row clearfix">
			<input type="submit" name="login" value="Login"/>
		</div>
	</form>
</div>
<div class="fright">
	If you dont have an account <a href="/user/register">Regitere here</a>
</div>