<div class="bannerWrapper" style="background-image:url('/Project/1_Website/Design/Pages/primary/home/images/astronout-banner.png');">
	<div class="slidingBanner mAuto">
		<div class="bannerDetails">
			<img class="fleft" src="/Project/1_Website/Design/Pages/primary/home/images/spaceship.png"/>
			<div>
				<h1>The Space Collection</h1>
				<p>Remember when you were young and you used to wait for all the new events of space exploration? Relive those moments with these brand new collectibles.</p>
				<a href="" class="mTl fleft btnOrLink bgRed">See the Collection</a>
			</div>
		</div>
		<ul class="slideIndicator">
			<li class="active"></li>
			<li></li>
			<li></li>
			<li class="last"></li>
		</ul>
	</div>
</div>
<!-- test-->
<div class="midSectionWrapper mAuto">
	<div class="fleft featuredProductWrapper">
		<h2 class="fontColorRed">Featured Products</h2>	
		<? $this->displayApplicationBlock('Products','displayFeaturedProducts'); ?>
		<a class="seeMoreProducts fwB fright show" href="/">See More Products</a>
	</div>
	<div class="fright otherLinkWrapper">
		<div class="topLinks">
			<div>
				<h3>Everyone deserves a Model</h3>
				<p>
				At Showcase Models, we believe that everyone deserves a handcrafted model plane or ship to remind them of a truly great time in their life.
				</p>
			</div>
			<? for($i=1; $i<=3; $i++) { ?>
				<div class="otherLinks">
					<div class="fleft otherLinksDescription">
						<h4>See the love and care</h4>
						It take 8 years up to years to become<br/>
						master model maker..
					</div>	
					<img class="fright" src="/Project/1_Website/Design/Pages/primary/home/images/other-links-image.png"/>
				</div>
			<? } ?>
		</div>
		<div class="aboutWebsite">
			For over 35 years, our model airplanes have been bought by blah blah. I wondered as lonely as a cloud when all of a sudden I saw a field of little yellow dafodils..
		</div>
	</div>
</div>