<div class="bannerWrapper" style="background-image:url('/Project/1_Website/Design/Main_Layout/images/temporary-images/banner-background.png');">
	<div class="slidingBanner mAuto">
	
		<div class="bannerDetails">
			<img src="/Project/1_Website/Design/Main_Layout/images/temporary-images/home-product-banner.png"/>
			<!-- 
			<div>
				<h1>The Space Collection</h1>
				<p>Remember when you were young and you used to wait for all the new events of space exploration? Relive those moments with these brand new collectibles.</p>
				<a href="" class="mTl fleft btnOrLink bgRed">See the Collection</a>
			</div>
			 -->
		</div>
		
		<ul class="slideIndicator">
			<li class="active"></li>
			<li></li>
			<li></li>
			<li class="last"></li>
		</ul>
	</div>
</div>
<div class="midSectionWrapper mAuto">
	<div class="fleft featuredProductWrapper">
		<h2 class="fontDarkGray">Featured Products</h2>	
		<? $this->displayApplicationBlock('Products','displayFeaturedProducts'); ?>
		<a class="seeMoreProducts fwB fright show fontDarkGray" href="/">
			See More Products
		</a>
	</div>
	<div class="fright otherLinkWrapper">
		<div class="topLinks">
			<div>
				<span class="fontColorBlue show">Everyone deserves a Model</span>
				<p>
				At Showcase Models, we believe that everyone deserves a handcrafted model plane or ship to remind them of a truly great time in their life.
				</p>
			</div>
			<? for($i=1; $i<=3; $i++) { ?>
				<div class="otherLinks">
					<div class="fleft otherLinksDescription">
						<h4>See the love and care</h4>
						<p>
						It take 8 years up to years to become<br/>
						master model maker..
						</p>
						<span class="show findOutMore">
							Find Out More
						</span>
					</div>	
					<img class="fright" src="/Project/1_Website/Design/Main_Layout/images/temporary-images/other-links-image.png"/>
				</div>
			<? } ?>
		</div>
		<div class="aboutWebsite">
			For over 35 years, our model airplanes have been bought by blah blah. I wondered as lonely as a cloud when all of a sudden I saw a field of little yellow dafodils..
		</div>
	</div>
	
	<div class="clearfix otherCompanies"></div>
</div>