<div id="upload-dialog" class="popupDialog uploadDialog">
	<h3>Upload Photo</h3>
		<form id="upload_image" enctype="multipart/form-data" method="POST">
			<input type="hidden" name="album_id" value="<?=$this->_get('size')->__get('album_id')?>">
			<input type="hidden" name="size_id" value="<?=$this->_get('size')->__get('size_id')?>">
			<input type="file" name="image_file[]" class="required trueInputFile" multiple>
			<div class="fakeInputFile sprite"><div id="fakeInputFile-text"><span></span></div></div>
			<div class="fright mBm">
				<input class="upload fleft mRxs " type="submit" name="upload_photo" value=" ">
				<span class="cancelUpload pointer  fleft closeDialog" title="cancel"></span>
			</div>
		</form>
</div>