<div class="mBl" id="actionHolder">
	<div class="clearfix">
		<h2 class="fleft">Category Listing</h2>
		<a href="#" class="newCategory fright" id="newCategory">new category</a>
	</div>
</div>
<div class="tableContainer">
	<table class="fullWidth filtered mBl">
		<thead>
			<tr>
				<th class="align_l" width="306px">Category Name</th>
				<th class="align_l" width="680px">Category Description</th>
				<th class="align_c" width="47px">Edit</th>
				<th class="align_c" width="60px">Delete</th>
			</tr>
		</thead>
	
	<?$i=1;?>	
		<tbody>
		<?for($i = 1; $i<5; $i++):?>
			<tr>
				<td>Category <?=$i?></td>
				<td>This is description <?=$i?></td>
				<td class="align_c"><a class="tablePencil" href="/category-manager/category/edit?category_id=<?=$i?>">edit</a></td>
				<td class="align_c"><a class="" href="/category-manager/category/delete?category_id=<?=$i?>">Delete</a></td>
			</tr>
		<?endfor?>
		</tbody>
	</table>
</div>