<div class="tableContainer">
	<div class="clearfix mBl">
		<h3 class="fleft posRel"><span class="editPencil">edit icon</span> EDIT CATEGORY</h3>
		<a href="/category-manager" class="backToListing categoryListing fright">back to category listing</a>
	</div>
	<div class="clearfix">
		<div class="fleft" id="productInfo">
			<p><strong>Information</strong></p>
			<p>Parent:<!-- for sub categories only -->
				<select class="hiLight">
					<option value="category 1">Category 1</option>
					<option value="category 2" selected="true">Category 2</option>
					<option value="category 3">Category 3</option>
					<option value="category 4">Category 4</option>
				</select>
			</p>
			<p>Title:<input type="text" name="title" value="Planes"></p>
			<p>Description:<textarea class="hiLight" name="category_description">Plastic models, 6 colors, etc.</textarea></p>
			<a class="save fright" href="<?=$_SERVER['REQUEST_URI']?>">Save</a>
		</div>
	</div>
</div>