<div class="tableContainer">
	
	<!-- notification shows up for newly created categories and sub categories-->
		<p class="fleft newItem notification hide"><span class="checkMark">check</span>Your category has been saved. You may now edit the details below.</p>
	<!-- end of notification-->
	<div class="clearfix mBl">
		<h3 class="fleft posRel">
			<span class="editPencil">edit icon</span> EDIT SUBCATEGORY
			<!-- if new CATEGORY use this -> <span class="editPencil">edit icon</span> NEW SUBCATEGORY -->
		</h3>
		<a href="/category-manager" class="backToListing categoryListing fright">back to category listing</a>
	</div>
	<div class="clearfix">
		<div class="fleft" id="productInfo">
			<p><strong>Details</strong></p>
			
			<p>Parent:
				<select class="hiLight">
					<option value="None">None</option>
					<option value="category 1">Category 1</option>
					<option value="category 2" selected="true">Category 2</option>
					<option value="category 3">Category 3</option>
					<option value="category 4">Category 4</option>
				</select>
			</p>
			
			<p>Title:<input type="text" name="title" value="Planes"></p>
			<div><p>Description:</p>
				<div class="fright"><textarea class="editor" name="description">Plastic models, 6 colors, etc.</textarea></div>
			</div>
			<a class="save fright" href="<?=$_SERVER['REQUEST_URI']?>">Save</a>
		</div>
		
		<div class="fleft" id="productImages">
			<div class="clearfix">
				<p><strong>Photo</strong></p>
				<p class="mTm">Banner Photo</p>
				<div class="clearfix">
					<span id="bannerPhoto" style="background-image: url('')"></span>
				</div>
				<span class="browse fright pointer">browse</span>
			</div>
			<div class="clearfix mTxl">
				<p><strong>Icon Photo</strong></p>
				<span id="iconPhoto" class="fleft" style="background-image: url('')"></span>
				<span class="browse icon fleft pointer mLl">browse</span>
			</div>
		</div>
	</div>
</div>