<div id="header" class="clearfix">
	<div id="welcome_section" class="clearfix hAuto overflow">
		<h1 id="logo" class="fleft">
			<a href="/"><img alt="Starfish Enterprise V4" title="Web Design Company in the Philippines" src="/Project/2_Enterprise/Design/Panels/header/images/Starfish-Enterprise-V3_logo.png"></a>
		</h1>
		<?= $this->displayApplicationBlock('User_Account','show_account_panel');?>
		
	</div>
	<?if(authorization::areWeLoggedIn()){?>
	<div id='navigation' class="pos_rel">
		<div id="slider_container" class="fleft">
			<?= navigation::displayNavigationForPages('primary','dashboard,settings,transactions');?>
		</div>
		<div id="navigation_controls" class="fleft hide"><span id="panLeft" title="pan left" class="sprite fleft pointer"></span><span id="panRight" title="pan right" class="sprite fright pointer"></span></div>
	</div>
		<?}?>
</div>