<!-- outer wrapper start-->
<div id="outer_wrapper" class="clearfix posRel">
<div id="photo_chooser"></div>

	<!-- left hand nav -->
	<div id="leftColumn" class="fleft"> 
	%%APPLICATION_LEFT_COLUMN%%
	<!-- left hand nav end -->
	</div> 
	
	<!-- content column start -->
	<div id="contentColumn" class="fright">
		<form method="POST">
			<div id="applicationContent" class="clearfix noPadding">
				%%APPLICATION_CONTENT%%
			
				<div id="applicationSideBar" class="fright pBl pTl">
					%%APPLICATION_SIDEBAR%%
				</div>
			</div>
		</form>
		
		<?if(applicationsRoutes::getInstance()->getCurrentControllerID() == 'category'):?>
			%%DELETE_CATEGORY_DIALOG%%
			
		<?elseif(applicationsRoutes::getInstance()->getCurrentControllerID() == 'subcategory'):?>
			%%DELETE_SUBCATEGORY_DIALOG%%
			
		<?elseif(applicationsRoutes::getInstance()->getCurrentControllerID() == 'product'):?>
			%%DELETE_PRODUCT_DIALOG%%
			
		<?endif;?>
	<!-- content column end -->
	</div>
	
</div>
<!-- outer wrapper end-->
<!-- %%ADD_CATEGORY_DIALOG%% -->
<!-- %%ADD_SUBCATEGORY_DIALOG%% -->
<!-- %%ADD_PRODUCT_DIALOG%% -->
<div class="popupDialog product_dialog addArticle_popUp"> 
<h3><img src="/Project/2_Enterprise/Design/Main_Layout/images/otherImages/plus.png" />Add a New Product</h3>
	<div class="subCategory_entity">
		<form method="POST" action="/products/product/add">
			<div class="mBxl">
				<strong>Product Title</strong><input class="validate[required,maxlength[45]] fright subCategory_entityTitle" type="text" name="title" maxlength="45">
			</div>
			<div class="mBxl">
				<strong>URL</strong><input class="fright subCategory_entityDescription" type="text" name="product_url" disabled="disabled"/>
			</div>
			<div id="button_container" class="fright mRs mBs">
				<input name="product_type" type="hidden" value="<?=routes::getInstance()->getCurrentTopLevelPageID();?>">
				<input name="category_id" type="hidden" value="">
				<input name="subcategory_id" type="hidden" value="">
				<input type="submit" class="save fleft mRs mTs" name="add_product" value=" ">
				<span class="mTs fleft pointer cancel" title="cancel"></span>
			</div>
		</form>
	</div>
</div>


<div class="transparent_background hide"></div>