<div class="tableContainer pAs">
	<table class="fullWidth filtered">
		<thead>
			<tr>
				<th>Title</th>
				<th>Product Code</th>
				<th>Description</th>
				<th>Price</th>
				<th>Category</th>
				<th>Action</th>
			</tr>
			<tr>
				<td><input type="text" name="filter_title"/></td>
				<td><input type="text" name="filter_product_code" /></td>
				<td><input type="text" name="filter_description" /></td>
				<td><input type="text" name="price" /></td>
				<td>
					<select>
						<option>Category 1</option>
						<option>Category 2</option>
						<option>Category 3</option>
						<option>Category 4</option>
					</select>
				</td>
				<td></td>
			</tr>
		</thead>
	
	<?$i=1;?>	
		<tbody>
		<?for($i = 1; $i<5; $i++):?>
			<tr>
				<td>Product <?=$i?></td>
				<td>P00<?=$i?></td>
				<td>Description<?=$i?></td>
				<td><?=$i?>00</td>
				<td>Category <?=$i?></td>
				<td><a href="/products-manager/product/edit?product_id=<?=$i?>">edit</a></td>
			</tr>
		<?endfor?>
		</tbody>
	</table>
</div>