<div class="tableContainer">
	<div class="clearfix mBl">
		<h3 class="fleft posRel">
			<span class="editPencil">edit icon</span> EDIT PRODUCT
			<!-- if new PRODUCT use this -> <span class="editPencil">edit icon</span> NEW PRODUCT -->
		</h3>
		<a href="/products-manager" class="backToListing productListing fright">back to product listing</a>
	</div>
	<div class="clearfix">
		<div class="fleft" id="productInfo">
			<p><strong>Details</strong></p>
			<p>Title:<input type="text" name="product_title" value="Product 1"></p>
			<p>Product Code:<input type="text" name="product_code" value="P001"></p>
			<div><p>Description:</p>
				<div class="fright"><textarea class="editor" name="description">This is a description</textarea></div>
			</div>
			<p id="specifications">Specifications:<input type="text" name="product_specification[]" value="P001"></p>
			<span class="addSpecificationText fright pointer mBl">add category</span>
			<p>Price:<input type="text" name="price" value="$100.00"></p>
			<p id="category"><span class="fleft">Category/<br/>Subcategory</span>
				<select name="category[]" class="mBs">
					<option value="new category">New Category</option>
					<option value="category 1">Category 1</option>
					<option value="category 2">Category 2</option>
					<option value="category 3">Category 3</option>
					<option value="category 4">Category 4</option>
				</select>
			</p>
			<span class="addCategoryText fright pointer">add category</span>
		</div>
		<div class="fright" id="productImages">
			<p><strong>Photo</strong></p>
			<div class="clearfix">
				<?for($i=0; $i < 5; $i++):?>
					<div class="imageContainer <?=($i == 1) ? 'selected' : ''?>">
						<?$image = '';?>
						<?if($i == 0):?>
							<span class="selectedCover">COVER</span>
							<?$image = '/Project/2_Enterprise/Design/Main_Layout/images/temporary/product-image.jpg'?>
						<?endif;?>
						<span class="imageHolder" style="background-image:url('<?=$image?>')"></span>
					</div>
				<?endfor;?>
			</div>
			<div class="clearfix mTl mBxl">
				<span class="addPhotoText fright pointer">add photo</span>
				<span class="deletePhotoText fright pointer mHxl">delete photo</span>
				<span class="makeCoverPhotoText fright pointer">make cover photo</span>
			</div>
		</div>
	</div>
	<div id="productActions" class="fright mTxxl">
		<a class="saveChanges fright" href="<?=$_SERVER['REQUEST_URI']?>">Save</a>
		<a class="deleteProduct fright mHl" href="<?=$_SERVER['REQUEST_URI']?>">delete product</a>
		<a class="unpublish fright" href="<?=$_SERVER['REQUEST_URI']?>">Unpublish</a>
	</div>
</div>