<!--************************************** CSS LINKS **************************************-->
    
<link rel="stylesheet" href="<?=STAR_DESIGN_MAINLAYOUT?>/css/main.css" type="text/css" media="screen, projection" />
<link rel="stylesheet" href="<?=STAR_DESIGN_MAINLAYOUT?>/css/typography.css" type="text/css" media="screen, projection" />
<link rel="stylesheet" href="<?=STAR_DESIGN_MAINLAYOUT?>/css/screen.css" type="text/css" media="screen, projection" />
<link rel="stylesheet" href="<?=STAR_DESIGN_MAINLAYOUT?>/css/normalize.css" type="text/css" media="screen, projection" />
<!-- <link rel="stylesheet" href="<?=STAR_DESIGN_MAINLAYOUT?>/css/responsive.css" type="text/css" media="screen, projection" /> -->
