<div class="extendedFooter">
	<footer class="mAuto">
		<div class="footerLinkWrapper clearfix">
			<div class="linkColumn">
				<h4>Learn More</h4>
				<ul>
					<li><a href="">About Us</a></li>
					<li>Careers</li>
					<li>Our Work</li>
					<li>Business Sales</li>
					<li>Customer Service</li>
					<li>Order Tracking</li>
					<li>Shipping/Delvery</li>
					<li>Return/Exchanges</li>
				</ul>
			</div>
			<div class="linkColumn">
				<h4>Our Showcase Models</h4>
				<ul>
					<li>Military</li>
					<li>Private</li>
					<li>Airlines</li>
					<li>NASA</li>
					<li>Maritime</li>
					<li>Customized</li>
				</ul>
			</div>
			<div class="linkColumn">
				<h4>Stay in Touch</h4>
				<ul>
					<li>Facebook</li>
					<li>Twitter</li>
					<li>Google Plus</li>
					<li>Pinterest</li>
					<li>Flickr</li>
					<li>Linkedin</li>
					<li>Youtube</li>
				</ul>
			</div>
			<div class="linkColumn">
				<h4 class="footerLogo"></h4>
				<div class="clearfix questionCall">
					Question? Call
					<br/>
					<span class="contactNumber">1-888-882-2323</span>
				</div>
				<ul>
					<li>Help</li>
					<li>FeedBack</li>
					<li>Contact Us</li>
				</ul>
			</div>
		</div>
	</footer>
	<div class="footerBottomWrapper">
		<div class="footerBottomLinks mAuto">
			<?=navigation::displayNavigationForPages('tertiary'); ?>
		</div>
	</div>
</div>

