<div class="popupDialog product_dialog addSubCategory_popUp">
<h3><img src="/Project/2_Enterprise/Design/Main_Layout/images/otherImages/plus.png" />Create New Subcategory</h3>
	<div class="subCategory_entity">
		<form method="POST" action="/products/subcategory/add">
			<div class="mBxl">
				<strong>Subcategory Title</strong><input class="validate[required,maxlength[45]] fright subCategory_entityTitle" type="text" name="title" maxlength="45">
			</div>
			<div class="mBxl">
				<strong>Url</strong><input class="fright subCategory_entityDescription" type="text" name="subcategory_url" maxlength="45" readonly>
			</div>
			<div class="mBxl">
			<div id="button_container" class="fright mRs mBs">
				<input type="hidden" name="category_id" value="">
				<input type="submit" class="save fleft mRs mTs" name="add_subcategory" value="">
				<span class="mTs fleft pointer cancel" title="cancel"></span>
			</div>
		</form>
	</div>
</div>